# Generated by Django 4.0.4 on 2022-04-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableA', '0005_sem8_sem7'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem2',
            name='subject_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
