# Generated by Django 4.0.4 on 2022-04-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableA', '0006_sem2_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sem1',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sem2',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sem3',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sem4',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sem5',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sem6',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sem7',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sem8',
            name='date',
        ),
        migrations.AddField(
            model_name='sem1',
            name='subject_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem3',
            name='subject_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem4',
            name='subject_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem5',
            name='subject_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem6',
            name='subject_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem7',
            name='subject_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem8',
            name='subject_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
