# Generated by Django 4.0.4 on 2022-05-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableA', '0007_remove_sem1_date_remove_sem2_date_remove_sem3_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem1',
            name='Faculty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem2',
            name='Faculty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem3',
            name='Faculty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem4',
            name='Faculty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem5',
            name='Faculty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem6',
            name='Faculty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem7',
            name='Faculty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sem8',
            name='Faculty',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
